name: etherscan_api
description: A dart library to access the etherscan.io apis. 
version: 1.0.0-beta
homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0-prev3
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  logger: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
